package com.godker.game.objects

import kotlinx.serialization.Serializable

@Serializable
enum class ObjectType (val id: Int){
    USE_ONCE(1),
    WEAPON(2),
    ARMOUR(3),
    TREES(4),
    MONEY(5),
    DOORS(6),
    CONTAINERS(7),
    POSTERS(8),
    KEYS(9),
    FORUMS(10),
    POTIONS(11),
    DRINKS(13),
    WOOD(14),
    CAMPFIRE(15),
    SHIELD(16),
    HELMET(17),
    RING(18),
    PORTAL(19),
    ORE_DEPOSIT(22),
    MINERALS(23),
    SCROLLS(24),
    INSTRUMENTS(26),
    ANVIL(27),
    FORGE(28),
    SHIPS(31),
    ARROWS(32),
    EMPTY_BOTTLE(33),
    FILLED_BOTTLE(34),
    UNUSED(35),
    ELFIC_TREE(36),
    BAGS(37),
    FISHES(38),
    ANY(1000)
}

@Serializable
data class Object (
    val name: String,
    val type: ObjectType,
    val grhId: Int? = null,
    val grh2Id: Int? = null,
    val canStab: Boolean? = null,
    val canSlash: Boolean? = null, //??? terrible naming
    val spellId: Int? = null,
    val forumId: String? = null,
    val oreId: Int? = null,
    val ingotId: Int? = null,
    val isProjectile: Boolean? = null,
    val isAmmunition: Boolean? = null,
    val crucial: Boolean? = null,
    val isNewbie: Boolean? = null,
    val minHp: Int? = null,
    val maxHp: Int? = null,
    val minSta: Int? = null,
    val potionType: Int? = null, //TODO enum?
    val maxModifier: Int? = null,
    val minModifier: Int? = null,
    val effectDuration: Int? = null,
    val minSkill: Int? = null,
    val minHit: Int? = null,
    val maxHit: Int? = null,
    val minHunger: Int? = null,
    val minThirst: Int? = null,
    val defense: Int? = null,
    val minDefense: Int? = null,
    val maxDefense: Int? = null,
    val clothing: Int? = null,
    val weaponAnimation: Int? = null,
    val dwarfsWeaponAnimation: Int? = null,
    val shieldAnimation: Int? = null,
    val helmetAnimation: Int? = null,
    val value: Int? = null,
    val isClosed: Boolean? = null,
    val usesKey: Boolean? = null,
    val radius: Int? = null,
    val bagType: Int? = null,
    val areGloves: Boolean? = null,
    val openedId: Int? = null,
    val closedId: Int? = null,
    val closedWithKeyId: Int? = null,
    val dwarfRace: Boolean? = null,
    val drowRace: Boolean? = null,
    val elfRace: Boolean? = null,
    val gnomeRace: Boolean? = null,
    val humanRace: Boolean? = null,
    val women: Boolean? = null,
    val men: Boolean? = null,
    val canPoison: Boolean? = null,
    val canParalyze: Boolean? = null,
    val canGrab: Boolean? = null,
    val ironIngot: Int? = null,
    val silverIngot: Int? = null,
    val goldIngot: Int? = null,
    val wood: Int? = null,
    val elficWood: Int? = null,
    val forgeSkill: Int? = null,
    val woodworkSkill: Int? = null,
    val text: String? = null,
    val forbiddenClasses: IntArray? = null,
    val snd1: Int? = null,
    val snd2: Int? = null,
    val snd3: Int? = null,
    val royal: Boolean? = null,
    val chaos: Boolean? = null,
    val doesNotDrop: Boolean? = null,
    val staffPower: Int? = null,
    val staffDamageBonus: Int? = null,
    val minMagicDefense: Int? = null,
    val maxMagicDefense: Int? = null,
    val bonus: Int? = null, //Refuerzo
    val log: Boolean? = null,
    val noLog: Boolean? = null,
    val upgrade: Int? = null
    ){
}